spring:
  profiles: 
    active:
    - dev
    include: 
    - init
    - develop

  
  datasource:
    url: jdbc:mysql://localhost:3306/ECOMER_TEST?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 990841
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa: 
    hibernate: 
      show-sql: true
    properties: 
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.physical_naming_strategy: me.alanx.ecomer.core.model.naming.DefaultNamingStrategy
  
  freemarker: 
    enabled: false
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
  devtools:
    restart:
      additional-paths: .
      additional-exclude: "**/webapp/**/*.jsp,**/webapp/**/*.js,**/webapp/**/*.css,**/webapp/**/*.html"
      
    
    
    
server: 
  #tomcat: 
    #additional-tld-skip-patterns: "*.jar"
  session: 
    timeout: 120000
    cookie: 
      max-age: 120000
ecomer: 
  authorization: 
    json: classpath:authorizations-default.json
    
    
# =====================================    
# Legacy configurations to be refactored
# =====================================
MULTIPLE_PRICE_AVAILABILITY: false
INDEX_PRODUCTS: true
# Images
PRODUCT_IMAGE_WIDTH_SIZE: 400
PRODUCT_IMAGE_HEIGHT_SIZE: 400
CROP_UPLOADED_IMAGES: false
# Upload image validations
PRODUCT_IMAGE_MAX_HEIGHT_SIZE: 2000
PRODUCT_IMAGE_MAX_WIDTH_SIZE: 4000
PRODUCT_IMAGE_MAX_SIZE: 9000000
IMAGE_FORMATS: jpg|png|gif

POPULATE_TEST_DATA: true
SHOP_SCHEME: http
# when removing the context path from the url put that value to blank (nothing) 
# otherwise put the uri for the web app eg /sm-shop -->
CONTEXT_PATH: 
URL_EXTENSION: .html
# Google maps key
shopizer.googlemaps_key: YOUR-KEY-HERE
#https://www.google.com/recaptcha/admin/create
# == to be used with localhost ==
#shopizer.recapatcha_public_key: 6LefQwsTAAAAAJWgJfNq_LgUwYunqct2x-EBr_CY
#shopizer.recapatcha_private_key: 6LefQwsTAAAAAM667PyQxTLkSfQ4P0YYeN5DQDTc
#shopizer.recapatcha_url: "https://www.google.com/recaptcha/api/siteverify"
# ==
# express checkout url
PAYPAL_EXPRESSCHECKOUT_SANDBOX: "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token="
PAYPAL_EXPRESSCHECKOUT_PRODUCTION: "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token="
PAYPAL_EXPRESSCHECKOUT_REGULAR: "_express-checkout&token="
PAYPAL_EXPRESSCHECKOUT_MOBILE: "_express-checkout-mobile&token="
    